In [60]:
%%timeit
'''双列表推导效率最高'''
import numpy as np 
a = [{"ids":(0,i)}for i in range(10000) ]
b = [v for i in a for v in i['ids']]
c = list(set(b))
#print(c)

100 loops, best of 3: 3.66 ms per loop


In [57]:
%%timeit
'''列表推导次之,但是经过多次转换效率降低'''
import numpy as np 
a = [{"ids":(0,i)}for i in range(1000) ]
b = np.array([list(v['ids']) for v in a]).flatten()
c = list(set(b))
#print(c)

1000 loops, best of 3: 810 µs per loop


In [59]:
%%timeit
'''循环速度最慢，尽量用单循环，并且循环计算尽量少'''
import numpy as np 
a = [{"ids":(0,i)}for i in range(10000) ]
b = []
for d in a:
    t =d['ids']
    b.append(t[0])
    b.append(t[1])
c=list(set(b))
#print(c)

100 loops, best of 3: 4.89 ms per loop


In [53]:
%%timeit
'''循环速度最慢，尽量用单循环，并且循环计算尽量少'''
import numpy as np 
a = [{"ids":(0,i)}for i in range(100) ]
b = []
for i in range(len(a)):
    t =a[i]['ids']
    b.append(t[0])
    b.append(t[1])
c=list(set(b))
#print(c)

10000 loops, best of 3: 45.4 µs per loop


In [47]:
%%timeit
'''列表推导+fun'''
import numpy as np 
a = [{"ids":(0,i)}for i in range(100) ]
b =[]
def f(b,dt):b+=list(dt['ids'])
e = [f(b,d) for d in a]
c = list(set(b))
#print(c)

10000 loops, best of 3: 58.6 µs per loop


In [2]:
%%timeit
'''列表推导+fun'''
import numpy as np 
a = [{"ids":(0,i)}for i in range(100) ]
b =[]
def f(b,dt):
    t = dt['ids']
    b.append(t[0])
    b.append(t[1])
e = [f(b,d) for d in a]
c = list(set(b))
#print(c)

10000 loops, best of 3: 59.4 µs per loop


In [1]:
%%timeit
'''列表推导+fun'''
import numpy as np 
a = [{"ids":(0,i)}for i in range(100) ]
b =[]
d = (i for v in a for i in v['ids'])
for i in d:b.append(i)
c = list(set(b))
#print(c)

The slowest run took 15792.67 times longer than the fastest. This could mean that an intermediate result is being cached.
1 loop, best of 3: 50.5 µs per loop


In [14]:
%%timeit
import math as m
N = 1000
for i in range(N):
    for j in range(N):
       a = 1+1
       b = m.sin(a)

10 loops, best of 3: 170 ms per loop


In [22]:
%%timeit
import numpy as np
N = 1000
for i in range(N):
    for j in range(N):
       pass

100 loops, best of 3: 17 ms per loop


In [19]:
%%timeit
import numpy as np
N = 1000
for i in np.arange(N):
    for j in np.arange(N):
       pass

10 loops, best of 3: 42 ms per loop


In [9]:
%%timeit
N = 1000
a=[j for i in range(N) for j in range(N)]

10 loops, best of 3: 64.1 ms per loop


In [12]:
%%timeit
N = 1000
a=(j for i in range(N) for j in range(N))
for i in a:b=1+1

10 loops, best of 3: 63.1 ms per loop


In [21]:
%%timeit
import numpy as np
N = 1000
a=(j for i in np.arange(N) for j in np.arange(N))
for i in a:b=1+1

10 loops, best of 3: 91.5 ms per loop


In [16]:
%%timeit
import math as m
N = 1000
a=(j for i in range(N) for j in range(N))
for i in a:
       b = 1+1
       c = m.sin(b)

1 loop, best of 3: 227 ms per loop


In [34]:
#%%timeit
import math as m
import numpy as np
N = 10
a = np.arange(N*N).reshape(N,N)
for i ,x in enumerate(a):
    print(i)
    print(x)


0
[0 1 2 3 4 5 6 7 8 9]
1
[10 11 12 13 14 15 16 17 18 19]
2
[20 21 22 23 24 25 26 27 28 29]
3
[30 31 32 33 34 35 36 37 38 39]
4
[40 41 42 43 44 45 46 47 48 49]
5
[50 51 52 53 54 55 56 57 58 59]
6
[60 61 62 63 64 65 66 67 68 69]
7
[70 71 72 73 74 75 76 77 78 79]
8
[80 81 82 83 84 85 86 87 88 89]
9
[90 91 92 93 94 95 96 97 98 99]


In [20]:
%%timeit
import math as m
import numpy as np
N = 1000
a = np.arange(N*N).reshape(N,N)
for k,i in enumerate(a):
    for l,j in enumerate(i):
        a[k,l] *= k



1 loop, best of 3: 432 ms per loop


In [69]:
%%timeit
import math as m
import numpy as np
N = 2000
M= 2000
a = np.arange(N*M).reshape(N,M)
for k in range(N):
    for l in range(M):
        a[k,l] *= k


C:\Users\xzl\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in long_scalars
  


1 loop, best of 3: 4.17 s per loop


In [62]:
%%timeit
import math as m
import numpy as np
N = 1000
a = np.arange(N*2).reshape(N,2)
#print(a)
b=[k*j for k, i in enumerate(a) for j in i]#采用enumerate函数效率特别低
b=np.array(b).reshape(10,-1)
#print(b)

1000 loops, best of 3: 1.35 ms per loop


In [78]:
#%%timeit
import math as m
import numpy as np
N = 3
M = 3
a = np.arange(N*M).reshape(N,M)
k = 0
f = lambda k: k+1
b = [j*k for i in a if f(k) > k  for j in i]
print(b)


[0, 0, 0, 0, 0, 0, 0, 0, 0]
